### ISSUE TITLE
Use recent confluent version

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/RADAR-Docker#120]
We should move to Confluent 4.1.0 with Apache Kafka 1.1.0.
https://docs.confluent.io/4.1.0/release-notes.html

Includes scalability, stability, connector and KSQL updates.

**Comment by afolarin** [comment]
Agree. :+1:

**Comment by yatharthranjan** [comment]
Tested the upgrade on test env at https://radar-backend.co.uk/
The steps followed were - 
Kafka Upgrade from 3.2.1 to 4.1.0

- **Recreate each broker with 4.1.0 kafka image for Rolling upgrade**
`sudo docker-compose up -d --no-deps --force-recreate kafka-1`
**Wait 1 min**
`sudo docker-compose up -d --no-deps --force-recreate kafka-2`
**Wait 1 min**
`sudo docker-compose up -d --no-deps --force-recreate kafka-3`

- **Recreate zookeeper with new version 4.1.0**
`sudo docker-compose up -d --no-deps --force-recreate zookeeper`
- **update all the clients like schema registry, rest proxy, etc to 4.1.0** in docker-compose file

- **Run the install script**
`./install-radar-stack.sh `

The upgrade seems to be stable and no errors occurred with the above procedure. I think we can move over to Confluent 4.1.0 in the repo.
Also do you guys have any more suggestion on the process of upgrading ?

**Comment by blootsvoets** [comment]
Good job! Sounds like a plan!

Then whenever we make an update to the backend or connectors, we can make the same upgrades to the client code. But indeed the server should go first.

**Comment by yatharthranjan** [comment]
Yes agreed!

**Comment by yatharthranjan** [comment]
Closed by #124
