### ISSUE TITLE
kafka-init fails due to avro tools not found

### ISSUE THREAD

**Issue by cgreenhalgh** [RADAR-base/RADAR-Docker#194]
`bin/radar-docker install` gets as far as running kafka-init, which outputs:
```
Compiling schemas...
===> Independent schemas:
merged/commons/active/notification/notification.avsc
...
===> Dependent schemas:
merged/commons/active/thincit/thinc_it_code_breaker.avsc
merged/commons/active/thincit/thinc_it_pdq.avsc
merged/commons/active/thincit/thinc_it_spotter.avsc
merged/commons/active/thincit/thinc_it_symbol_check.avsc
merged/commons/connector/fitbit/fitbit_activity_log_record.avsc
merged/commons/stream/aggregator/aggregate_list.avsc
### FAILURE ###
```
On further inspection, in kafka-init image 
```
bash-4.4# ls -l /usr/share/java/avro-tools.jar
-rw-r--r--    1 root     root           357 Jul 15 08:36 /usr/share/java/avro-tools.jar
...
<p>The requested URL /avro/avro-1.8.2/java/avro-tools-1.8.2.jar was not found on this server.</p> 
```
This in turn seems be because the release of avro 1.9.0 (May 2019) has resulted in release 1.8.2 no longer being in the general apache CDN for avro, only in release the [archive](http://archive.apache.org/dist/avro/avro-1.8.2/java)

**Comment by blootsvoets** [comment]
This has been fixed in the dev branch with #192, but it has not yet been released to master. Could you try to use the dev branch for now? @yatharthranjan could you please make a new release?

**Comment by cgreenhalgh** [comment]
yes, dev branch was fine.

**Comment by yatharthranjan** [comment]
@cgreenhalgh The master branch has also been updated now
