### ISSUE TITLE
installation depends on "keytool" (missing pre-requisite)

### ISSUE THREAD

**Issue by cgreenhalgh** [RADAR-base/RADAR-Docker#195]
The readme and [install guide](https://radar-base.org/index.php/2019/02/13/how-to-install-radar-base-using-radar-docker/) don't mention 'keytool' as a pre-requisite, but it is needed by `RADAR-Docker/dcompose-stack/radar-cp-hadoop-stack/bin/keystore-init` which is called by the standard install script `.../lib/perform-install.sh` (from `.../bin/radar-docker install`).

workaround, e.g. install `openjdk-8-jre-headless`

**Comment by blootsvoets** [comment]
Thanks for the note! I've updated the README in #196. @yatharthranjan could you please update the install guide linked in the issue.

**Comment by yatharthranjan** [comment]
Ok done 👍

**Comment by cgreenhalgh** [comment]
@yatharthranjan just to mention that something seems to have broken in the [install guide](https://radar-base.org/index.php/2019/02/13/how-to-install-radar-base-using-radar-docker/) formatting (all the steps appear nesting when i view it)
