### ISSUE TITLE
Test with multi-host networking solution

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/RADAR-Docker#2]
Lots of options here.. depends on how we want to go

*multi-host networking*
overlay (not sure about performance)
Weave.io 
Flannel

*full clustered option*
kubernettes
docker-swarm

**Comment by afolarin** [comment]
@blootsvoets  need to test overlay networking as a solution here -- would be great to know this is possible.

> Bridge networking is currently only supported on a single host. For multiple hosts, you will need to use overlay networks which are not currently supported.

http://docs.confluent.io/3.0.1/cp-docker-images/docs/intro.html

**Comment by blootsvoets** [comment]
OK, had a closer look and `docker-compose` is not yet compatible with overlay networks or multi-host deployment (the main docker-swarm features): docker/docker#24107. It is expected to work in a future version of docker, but right now the only way to use overlay networks and multi-host deployment is to use the

```
docker service create IMAGE
```

[command](https://docs.docker.com/engine/reference/commandline/service_create/). That means that all configuration we made in `docker-compose.yml` has to be manually specified. Also available in a future version of docker is to run (experimental):

```
docker-compose bundle radarstack
docker deploy radarstack
```

In Docker engine version 1.12.5 on Mac, the `docker deploy` command is not yet available in the stable build.

Kubernetes might not face these problems, I haven't tested it.

**Comment by afolarin** [comment]
@blootsvoets yes, sounds like there are people doing this (a bit old and not using the official images) http://www.defuze.org/archives/351-running-a-zookeeper-and-kafka-cluster-with-kubernetes-on-aws.html 

In any case this would only be needed for the post pilot deployments.

**Comment by afolarin** [comment]
If you want a quick Docker Swarm cluster (on EC2 or Azure) this works pretty good for testing. But as you say we are restricted to `docker-service` and overlay won't work anyway.
https://blog.docker.com/2016/06/azure-aws-beta/
https://beta.docker.com/docs/deploy/

But not sure how much this adds at the moment, seems like we might hold fire on this issue for the present? 

or go for a Kubernetes option if multihost deploy is essential.

**Comment by afolarin** [comment]
@blootsvoets @fnobilia there are some developments in this on swarm see docker-compose v3 and Docker v1.13.

```
$ docker deploy --compose-file docker-compose.yml
```

See

https://hackernoon.com/deploy-docker-compose-v3-to-swarm-mode-cluster-4159e9cca712#.r9dbpbpv4

**Comment by afolarin** [comment]
@blootsvoets I think this is working, exception of hadoop. Tested on a 3 node swarm cluster using overlay networks #21

**Comment by blootsvoets** [comment]
Attachable overlay networks in docker-compose v3 do not seem working (yet): docker/docker#30191. Another solution would be needed to get data out of a hadoop cluster. One of the options still being, creating a network with `--attachable` flag before running.

**Comment by afolarin** [comment]
> One of the options still being, creating a network with --attachable flag before running

AFAIK That's the only way at present

**Comment by yatharthranjan** [comment]
Closing this now since there is Kubernetes and distributed-dcompose stacks now.
