### ISSUE TITLE
Kafka socket error during installation (Socket error occurred: zookeeper-3/172.18.0.2:2181: Connection refused)

### ISSUE THREAD

**Issue by sallymoon10** [RADAR-base/RADAR-Docker#228]
Hello, I am trying to install RADAR-BASE on AWS E2 Linux server. I followed the instructions to install the RADAR-BASE platform here: https://radar-base.org/index.php/2019/02/13/how-to-install-radar-base-using-radar-docker/

However during installation, I've encountered the following errors:

![image](https://user-images.githubusercontent.com/14798003/98425345-02202400-2052-11eb-914b-dbc9884e748d.png)
![image](https://user-images.githubusercontent.com/14798003/98425353-064c4180-2052-11eb-945e-b81aecf894d4.png)
![image](https://user-images.githubusercontent.com/14798003/98425348-03e9e780-2052-11eb-8272-442058996e01.png)
![image](https://user-images.githubusercontent.com/14798003/98425360-08160500-2052-11eb-9af4-0694270f89d2.png)

It seems like the main error is 'Socket error occurred: zookeeper-3/172.18.0.2:2181: Connection refused'. 

I am currently on the dev branch and I have ran git checkout docker-compose.yml as suggested in a previous issue (https://github.com/RADAR-base/RADAR-Docker/issues/224).

How should I go about fixing this? Let me know if you need any files from me to help with debugging.

**Comment by ObitoSigma** [comment]
When this happened to me, it was because my instance did not meet the server specifications. Check to see if your instance has 16 GB storage and a 4-core CPU. I've been using t2.xlarge with a 16 GB volume.

**Comment by sallymoon10** [comment]
> When this happened to me, it was because my instance did not meet the server specifications. Check to see if your instance has 16 GB storage and a 4-core CPU. I've been using t2.xlarge with a 16 GB volume.

Thanks a lot for your help! I'll definitely check that out :)

**Comment by afolarin** [comment]
cc/ @nivemaham might be useful to provide guideline spec in the prerequisite https://radar-base.org/index.php/2019/02/13/how-to-install-radar-base-using-radar-docker/
