### ISSUE TITLE
Gateway Errors?

### ISSUE THREAD

**Issue by JustSamzy** [RADAR-base/RADAR-Docker#243]
Hi there,

We are a university group project and we have been trying to get our management portal up and running.

We have confirmed the confluent aspect is up and running, however whenever we try to run the radar-docker containers we seem to be running into the same issues. I have attached the "errors" that are stored in the gateway_1 container which we cant seem to figure out. I have also attached a copy of the gateway.yml file which is identical to the one on GitHub. All other containers are healthy (webserver shows as Up with ports 80 and 443, then management portal goes unhealthy due to the gateway)

Any help would be greatly appreciated!

![gateway-yml](https://user-images.githubusercontent.com/71432974/110957269-5cecc380-8343-11eb-95e5-8bc5619aa1a4.PNG)

![fresh-errors](https://user-images.githubusercontent.com/71432974/110957427-8574bd80-8343-11eb-8fec-09b606b76f54.PNG)

**Comment by iDmple** [comment]
We have that issue as well, and sofar it seems that it doesn't prevent RADAR-base from working, but we are interested in a solution.

**Comment by JustSamzy** [comment]
We have someone on the RADAR-base Slack channel as this is for s student project and this was the response given:

"These logs are not errors, just informational. They indicate that the gateway was started, stopped again and started again. The RADAR_IS_LOCATION_CONFIG is optional, and indeed it is better if it is not set. The oauth endpoint indicates that the Gateway will use managementportal for authentication."

The gateway is still unhealthy, but the management portal now loads on a web browser. But we are unable to log into the portal

**Comment by iDmple** [comment]
For the login, we had that issue too. It only works if you use letsencrypt. Self-signed and custom ssl certs break login. But maybe you don't have the same issue as we did.

**Comment by yatharthranjan** [comment]
fixed by #261
