### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Docker#252]
Migrate from Travis to GH actions. Preferably using docker secrets to log in to avoid hitting image pull limits.

**Comment by baixiac** [comment]
Hi, @yatharthranjan. Could you further elaborate which GH actions are needed for this repo?

**Comment by yatharthranjan** [comment]
HI @baixiac, essentially converting the [travis workflow](https://github.com/RADAR-base/RADAR-Docker/blob/master/.travis.yml) into GH actions in the first instance. It is a series of commands that run the stack and check it is healthy.

**Comment by yatharthranjan** [comment]
closed by #256
