### ISSUE TITLE
Separate the steps in CI to different jobs

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Docker#267]
Since the 3 different stacks can run independent of each other, it might be good to separate the run of hadoop, S3 and firebase messaging stacks into separate CI jobs, so these can be run in parallel and hence complete the CI on PRs faster.

**Comment by baixiac** [comment]
Although running jobs in parallel is attractive, consideration needs to be taken coz the limit on the maximum number of concurrent jobs currently applies to the entrie GitHub account. So setting the concurrent run for each job to one seems sensical.

**Comment by yatharthranjan** [comment]
closed by #269
